### ISSUE TITLE
[Discussion] Slash-Commands

### ISSUE THREAD

**Issue by msqueentired** [stevenpitts/makubot#267]
As of March 2021, the Discord API has added a new way of interacting with bots, [slash-commands](https://blog.discord.com/slash-commands-are-here-8db0a385d9e6).
<img src="https://miro.medium.com/max/1400/0*Q5CzShKq5zm3kzcv.png" />

## Pros of adding support
* Would allow users to interact with Makubot without using a prefix or pinging it
* Adds a native way to expose commands, syntax, and a description of them
## Cons of adding support
* [discord.py does not currently support these and likely will not for a long time.](https://github.com/Rapptz/discord.py/issues/6149#issuecomment-779329841) This would require using a [fork](https://github.com/discord-py-slash-commands/discord-py-interactions) and would [break some things](https://discord-py-slash-command.readthedocs.io/en/latest/faq.html#can-i-use-something-of-discord-py-s-in-this-extension), possibly requiring large rewrites of Makubot's codebase.
* Switching to the fork would require the project to switch back after discord.py implements this, as the fork would no longer need to exist and would stop being maintained.
* The primary thing I see Makubot get used for is image commands, and it wouldn't make sense to add slash support since there's enough of them to require pagination on `listreactions`.
----
There aren't enough people making commits to Makubot for adding this right now to not be a waste of time IMO, but I'd like to hear other's thoughts on it.

**Comment by lupomikti** [comment]
I think you're right about the effort being too much for this at the moment. So far I've only seen a few bots in the servers I'm in bother with it, and they're typically ones with larger user bases and more contributors. I don't think it should *never* be implemented, but it doesn't make a lot of sense to me to try to implement it at this time given the cons you've listed. It seems that if the functionality comes to discord.py in the near future, then there aren't many downsides and it would turn into a "nice to have" feature request.

**Comment by makusu2** [comment]
Oh yeah that's gonna be cool when it's mainstream!
Thank you for the suggestion ^_^
:smiling_face_with_three_hearts:

**Comment by msqueentired** [comment]
With discord.py getting deprecated, makubot as it stands right now will stop working within about 6mo. [Discord-py-slash](https://discord-py-slash-command.readthedocs.io/en/latest/faq.html#discord-py-is-dead-will-this-library-die-too) has indicated they do intend to maintain their library, so I'm going to look into the (hellish) prospect of porting the code over.

**Comment by makusu2** [comment]
> I'm going to look into the (hellish) prospect of porting the code over.

Why do you hate yourself
