### ISSUE TITLE
Make code less shitty

### ISSUE THREAD

**Issue by stevenpitts** [stevenpitts/makubot#271]
As of September 2021, the code is decidedly shitty.

## Pros of making code less shitty
* Code would be less shitty
## Cons of making code less shitty
* discord.py doesn't work well with Docker so that's already kinda a roadblock
* Last I checked, major python profiling tools don't play nicely with async code, so some of the shitty implementations are actually required
* Maku is a shitty developer
## Solutions
* Give up
* Wait and hope for Lust or Lupo to make the code less shitty

**Comment by msqueentired** [comment]
Don't worry, I plan on making solution #2 happen 😉
